server.http2.enabled: true

spring:
  main.banner-mode: "off"
  profiles:
    active: "INVALID_PROFILE"

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

app:
  envName: "INVALID_ENV"
  service:
      name: "example-service"
      qualifiedName: ${app.service.name}-${app.envName}
      q-name: ${app.service.name}-${app.envName}
  example:
    job:
      enabled: true
      min: 10
      max: 1000
      delay: "PT30S"
      items: [ "item-0", "item-1","item-2"]
      foo: ${SOME_ENV_VAR}

  tricky:
    a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q:
      - "d0"
      - "d1"
      - d3-${app.service.qualifiedName}